# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: Build Agent

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


stages:
- stage: NuGet
  displayName: 'NuGet'
  jobs:
  - job: Nuget
    displayName: 'Nuget'
    pool:
      name: Build Agent
    steps:
    - task: NuGetToolInstaller@1

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**\*.sln'
      feedsToUse: 'select'